# Generated by Django 5.2 on 2025-04-28 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_alter_pago_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AddField(
            model_name='pago',
            name='descripcion_tratamiento',
            field=models.TextField(default='Descripción no proporcionada'),
        ),
        migrations.AddField(
            model_name='pago',
            name='especialista_responsable',
            field=models.CharField(default='No asignado', max_length=100),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_paciente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='id_servicio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='nombre_paciente',
            field=models.CharField(default='Paciente desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipo_tratamiento',
            field=models.CharField(default='Tratamiento general', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
