# Generated by Django 5.2 on 2025-04-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pago_options_pago_descripcion_tratamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
