# Generated by Django 5.2 on 2025-04-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_pago_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='descripcion_tratamiento',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pago',
            name='especialista_responsable',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nombre_paciente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_tratamiento',
            field=models.CharField(default='', max_length=100),
        ),
    ]
