# Generated by Django 5.2 on 2025-04-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('recepcionista', 'Recepcionista'), ('paciente', 'Paciente'), ('especialista', 'Especialista')], default='paciente', max_length=20),
        ),
    ]
