# Generated by Django 5.2 on 2025-04-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('recepcionista', 'Recepcionista'), ('paciente', 'Paciente'), ('especialista', 'Especialista'), ('administrador', 'Administrador')], default='administrador', max_length=20),
        ),
    ]
